"""updated review table

Revision ID: cd2bd05978e2
Revises: 
Create Date: 2025-01-29 13:07:18.908972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2bd05978e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('rating_id', type_='foreignkey')
        batch_op.drop_column('rating_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'rating', ['rating_id'], ['id'])

    # ### end Alembic commands ###
